src/accounts/urls.py
from django.conf.urls import url

from .views import logout_page, GuestRegisterView, SettingsPageView,\
    activation_view, send_activation_mail, LoginView, RegisterView


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(
        r'^activation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activation_view,
        name='activation'
    ),
    url(r'^reactivate/(?P<user>[0-9A-Za-z_\-]+)/(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)/$',
        send_activation_mail,
        name='reactivate'
        ),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', logout_page, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^settings/$', SettingsPageView.as_view(), name='settings'),
    ]

src/carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_success, check_availability
from addresses.views import checkout_address_create_view, checkout_address_reuse_view


urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^availability/$', check_availability, name='check_availability'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^checkout/success$', checkout_success, name='checkout_success'),
]

src/sklep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from .views import home_page, AboutPageView, cookies_policy, regulations_page


urlpatterns = [
    url(r'^$', home_page, name='home_page'),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^analytics/', include("analytics.urls", namespace='analytics')),
    url(r'^regulations/$', regulations_page, name='regulations'),
    url(r'^cookies/$', cookies_policy, name='cookies'),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^marketing/', include("marketing.urls", namespace='marketing')),
    url(r'^cart/', include("carts.urls", namespace='carts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/wix/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url

from .views import wix_page

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url='https://biczysko.wix.com/foto')),
    url(r'^$', wix_page, name='wix'),
]

src/carts/models.py
from django.db import models
from django.conf import settings

from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product
User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        # qs = Cart.objects.filter(id=cart_id)
        qs = self.get_queryset().filter(id=cart_id)

        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            new_obj = True
            cart_obj = self.new(user=request.user)
            request.session['cart_id'] = cart_obj.id

        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user

        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user                = models.ForeignKey(User, null=True, blank=True)
    products            = models.ManyToManyField(Product, blank=True)
    total               = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    subtotal            = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    timestamp           = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    shipping_cost       = models.DecimalField(default=20.00, max_digits=10, decimal_places=2)


    objects = CartManager()

    def __str__(self):
        return  str(self.id)

    def product_list(self):
        return [product.id for product in self.products.all()]


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action in ['post_remove', 'post_add', 'post_clear']:
        products = instance.products.all()
        subtotal = sum([product.promo_price if (product.promo_price and product.promo_active) else product.price for product in products])
        instance.subtotal = subtotal
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal  + instance.shipping_cost
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.db.models import Q

from .models import Cart
from products.models import Product
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = cart_obj.products.all()

    context = {
        'total_price': cart_obj.subtotal,
        'basket_products': products,
        'cart': cart_obj
    }

    return render(request, "carts/home.html", context)


def cart_update(request):
    product_id = request.POST.get('product')
    add_another_multiple = request.POST.get('add_another_multiple')

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)

        except Product.DoesNotExist:

            messages.warning(request, 'Wystąpił błąd, produkt nie istnieje w bazie')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        # try add to cart another instance of same type multiple product
        if add_another_multiple:
            qs = get_another_multiple_product(product_obj, cart_obj)

            # if there is available another product -> add to cart
            if qs:
                new_product = qs[0]
                cart_obj.products.add(new_product)
            else:
                messages.warning(request, 'Brak dostępnych kolejnych produktów tego typu')

        else:
            if product_obj in cart_obj.products.all():
                cart_obj.products.remove(product_obj)
            else:
                cart_obj.products.add(product_obj)  # cart_obj.products.add(product_id)
                messages.success(request, 'Produkt został dodany do koszyka')

        request.session['cart_items_count'] = cart_obj.products.count()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def checkout_home(request):

    cart_obj, cart_created = Cart.objects.new_or_get(request) # create or get cart
    products = cart_obj.products.all()

    order_obj = None
    address_qs = None

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()

    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

    if request.session.get('success_order_id'):
        del request.session['success_order_id']

    if cart_created or cart_obj.products.count() == 0: # new empty cart or no products in cart so no checkout
        return redirect("carts:home")

    if billing_profile is not None: # Billing profile is available so we can create or update order
        order_obj, order_obj_created = Order.objects.new_or_get(cart_obj=cart_obj, billing_profile=billing_profile)
        address_qs = Address.objects.filter(billing_profile=billing_profile, current=True)

        # make_checkout flag is received via GET trough check_availability
        make_checkout = request.GET.get('make_checkout')

        del_shipping_address = request.POST.get('del_shipping_address')
        del_billing_address = request.POST.get('del_billing_address')

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            order_obj.save()
            del request.session["shipping_address_id"]

        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            order_obj.save()
            del request.session["billing_address_id"]

        if make_checkout:
            order_is_done = order_obj.check_if_done()
            if order_is_done:

                order_status = order_obj.mark_as_done()
                request.session['success_order_id'] = order_obj.order_id
                return redirect("carts:checkout_success")

        # delete current address from order and go back to choose another one
        if del_shipping_address or del_billing_address:
            if del_shipping_address:
                order_obj.shipping_address = None
                order_obj.save()
            elif del_billing_address:
                order_obj.billing_address = None
                order_obj.save()

            return redirect("carts:checkout")

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "basket_products": products,
        "address_qs": address_qs

    }

    return render(request, "carts/checkout.html", context)

def checkout_success(request):
    success_order_id = request.session.get('success_order_id')
    order_obj = Order.objects.get(order_id=success_order_id)
    success_user_email = order_obj.billing_profile.email
    success_order_total = str(order_obj.total)
    context = {
        'success_order_id': success_order_id,
        'success_user_email': success_user_email,
        'success_order_total': success_order_total
    }


    bought_products = order_obj.cart.products.all()
    for product in bought_products:
        product.make_selled()

    # Send order success mail
    send_order_success_mail(request, success_order_id, success_user_email, success_order_total, bought_products, order_obj)

    if request.session.get('cart_id'):
        del request.session['cart_id']
    if request.session.get('cart_items_count'):
        del request.session['cart_items_count']
    if request.session.get('guest_email_id'):
        del request.session['guest_email_id']
        messages.info(request, 'Zakończono sesję gościa')

    return render(request, "carts/checkout_success.html", context)


def get_another_multiple_product(product, cart_obj):
    # if possible return qs of available instances of same model of 'multiple type' product

    product_category = product.category
    product_model = product.model  # model is unique type field

    # constructing Q query :)
    queryClass = product.__class__.__name__
    queryField = 'model'
    queryFilter = queryClass + '___' + queryField

    # unpacking dict to kwargs hack
    qs = Product.objects.all_available().filter(category=product_category).filter(
        Q(**{queryFilter: product_model}))

    # filter out products which are already in cart
    qs = [prod for prod in qs if not prod in cart_obj.products.all()]

    return qs

def check_availability(request):
    next_get_url = request.GET.get('next_url')
    next_post_url = request.POST.get('next_url')
    make_checkout = request.POST.get('make_checkout')
    redirect_path = (next_post_url or next_get_url) or None

    cart_obj, cart_created = Cart.objects.new_or_get(request)  # create or get cart
    products = cart_obj.products.all()
    all_available = True

    for product in products:
        if product.selled == True:

            # try replace 'multiple' product with available one
            if product.category in product.MULTIPLE_PRODUCTS_CATEGORIES:

                qs = get_another_multiple_product(product, cart_obj)

                # if there is available another product -> replace
                if qs:
                    cart_obj.products.remove(product)
                    new_product = qs.first()
                    cart_obj.products.add(new_product)
                    continue

            # remove not available product from cart
            all_available = False
            cart_obj.products.remove(product)
            request.session['cart_items_count'] = cart_obj.products.count()

            messages.warning(request, f"Produkt {product} został usunięty z karty")

    if all_available is True:
        if make_checkout:
            redirect_path += "?make_checkout=True"

        return redirect(redirect_path)

    else:
        messages.warning(request, f"Ktoś Cię ubiegł, jeden z wybranych przez Ciebie produktów jest już niedostępny :(")
        return redirect("carts:home")


def send_order_success_mail(request, success_order_id, success_user_email, success_order_total, bought_products, order_obj):
    mail_subject = f"naklisze.pl - Potwierdzenie zamówienia nr {success_order_id}"
    message = render_to_string('carts/checkout_success_email.html', {
        'success_order_id': success_order_id,
        'success_user_email': success_user_email,
        'success_order_total': success_order_total,
        'bought_products': bought_products,
        'order': order_obj
    })
    email_msg = EmailMessage(
        mail_subject, message, to=[success_user_email, "naklisze@gmail.com"]
    )
    try:
        email_msg.send()
    except:
        messages.warning(request, f'Nastąpił błąd przy wysyłaniu potwierdzenia na adres {success_user_email}')

src/carts/templates/carts/checkout.html
{% extends "base_prod.html" %}

{% block content %}

    {% load static %}

    {% url 'carts:update' as update_cart_url %}
    {% url 'accounts:login' as login_url %}
    {% url 'accounts:guest_register' as guest_register_url %}
    {% url 'accounts:register' as register_url %}
    {% url 'carts:checkout_address_create' as checkout_address_create_url %}
    {% url 'carts:checkout_address_reuse' as checkout_address_reuse_url %}

    {% if not billing_profile %}

        {% include "carts/snippets/breadcrumbs.html" with page="Konto" %}

        <div class="container py-lg-5">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="text-secondary">Zaloguj się</h2>
                    {% include "snippets/form.html" with form=login_form next_url=request.build_absolute_uri button="Zaloguj" action_url=login_url login=True %}
                    <h4 class="text-info my-3"><a class="text-info font-weight-bold text-center" href="{{ register_url }}">Załóż konto</a> aby otrzymać 5% rabatu na każdy produkt!</h4>
                </div>
                <div class="col-md-6">
                    <h2 class="text-secondary">Kontynuuj jako gość</h2>
                    {% include "snippets/form.html" with form=guest_form next_url=request.build_absolute_uri button="Dalej" action_url=guest_register_url %}
                </div>
            </div>
        </div>

    {% else %}

        {% if not object.shipping_address or not object.billing_address %}


            {% if not object.shipping_address %}

            {% include "carts/snippets/breadcrumbs.html" with page="Adres" %}

            <div class="container my-5">
                <div class="row">
                     {% if address_qs %}
                        <div class="col-lg-6 mx-auto">
                            <h2 class="text-secondary">Wybierz adres z listy</h2>
                            {% include "addresses/snippets/reuse_address.html" with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse_url %}
                        </div>
                     {% endif %}
                </div>
                <div class="row">
                    <div class="col-lg-6 mx-auto">
                        <h2 class="text-secondary">Adres wysyłki</h2>
                        {% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri button="Dalej" action_url=checkout_address_create_url %}
                    </div>
                </div>
            </div>

            {% elif not object.billing_address %}

                {% include "carts/snippets/breadcrumbs.html" with page="Dane" %}

                <div class="container my-5">
                    <div class="row">
                        {% if address_qs %}
                            <div class="col-lg-6 mx-auto">
                                <h2 class="text-secondary">Wybierz dane z listy</h2>
                                {% include "addresses/snippets/reuse_address.html" with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse_url address_type="billing" %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col-lg-6 mx-auto">
                            <h2 class="text-secondary">Dane Kupującego</h2>
                            {% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri button="Dalej" action_url=checkout_address_create_url address_type="billing"%}
                        </div>
                    </div>
                </div>

            {% endif %}

        {% else %}

            {% include "carts/snippets/breadcrumbs.html" with page="Podsumowanie" %}

            <div class="container my-5">
                <div class="row my-5">
                    <div class="col-lg-6 text-center">
                        <h2 class="text-secondary my-5">Dane kupującego</h2>
                        {% for address_part in object.billing_address.print_address_html %}
                            &emsp;{{ address_part }}<br>
                        {% endfor %}
                        {% include "addresses/snippets/del_address.html" with action_url=request.build_absolute_uri del_address="del_billing_address" %}
                    </div>
                    <div class="col-lg-6 text-center">
                        <h2 class="text-secondary my-5">Adres wysyłki</h2>
                        {% for address_part in object.shipping_address.print_address_html %}
                            &emsp;{{ address_part }}<br>
                        {% endfor %}
                        {% include "addresses/snippets/del_address.html" with action_url=request.build_absolute_uri del_address="del_billing_address" %}
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Produkt</th>
                          <th scope="col">Cena</th>
                        </tr>
                    </thead>
                    <tbody>
                          {% for product in basket_products %}
                            <tr>
                              <th scope="row">{{ forloop.counter }}</th>
                                <td><p class="text-dark">{{ product.order_title }}</p></td>
                                {% if product.promo_active and product.promo_price %}
                                <td><strike>{{ product.price }}</strike>&emsp;{{ product.promo_price }} zł</td>
                                {% else %}
                                <td>{{ product.price }} zł</td>
                                {% endif %}
                            </tr>
                          {% endfor %}
                    </tbody>
                </table>

                <dl class="row my-3">
                    <dt class="col-sm-3">Koszt produktów:</dt>
                    <dd class="col-sm-9">{{ object.products_cost }} zł</dd>
                    <dt class="col-sm-3">Koszt przesyłki:</dt>
                    <dd class="col-sm-9">{{ object.shipping_cost }} zł</dd>
                    {% if object.logged_user_promo > 0 %}
                    <dt class="col-sm-3">Rabat:</dt>
                    <dd class="col-sm-9">{{ object.logged_user_promo }} %</dd>
                    {% endif %}
                    <dt class="col-sm-3 my-3"><strong>Całkowity koszt zamówienia:</strong></dt>
                    <dd class="col-sm-9 my-3 text-info"><strong>{{ object.total }} zł</strong></dd>
                </dl>
            </div>

                <div class="row my-5">
                    <div class="col centered mt-5" style="text-align:center">
                        {% include "carts/snippets/checkout_end_button.html" with next_url=request.build_absolute_uri %}
                    </div>
                </div>

        {% endif %}

    {% endif %}

{% endblock %}

src/carts/templates/carts/checkout_success.html
{% extends "base.html" %}

{% block content %}

    {% load static %}

    {% url 'accounts:register' as register_url %}
    {% url 'accounts:settings' as settings_url %}

            {% include "carts/snippets/breadcrumbs.html" with page="Sukces" %}

            <div class="container my-5">
                <div class="row my-5">
                    <div class="col">
                        <h2 class="text-secondary my-5">Dziękujemy,</h2>
                        <p>Zamówienie o numerze <strong>{{ success_order_id }}</strong> zostało przekazane do realizacji.</p>
                        <p>Potwierdzenie zamówienia jak i wszystkie niezbędne do realizacji informacje zostały wysłane na adres email: <strong>{{ success_user_email }}</strong></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <h4 class="text-secondary my-3">Prosimy o dokonanie wpłaty zgodnie z poniższymi danymi:</h4>
                        <p>Nr konta:<strong class="mx-2">1234 2345 3456 4566 0000 4566 6660</strong></p>
                        <p>Kwota:<strong class="mx-2">{{ success_order_total }} zł</strong></p>
                        <p>Tytuł przelewu:<strong class="mx-2">{{ success_user_email }}/{{ success_order_id }}</strong></p>
                    </div>
                </div>
                <div class="row my-4">
                    <div class="col">
                        {% if request.user.is_authenticated %}
                        <a class="text-dark text-nowrap" style="text-decoration: none;" href="{{ settings_url }}">
                            Status zamówienia możesz śledzić w panelu użytkownika<i class="fas fa-cog fa-2x mx-2 text-info"></i></a>
                        {% else %}
                        <a class="text-dark text-nowrap" style="text-decoration: none;" href="{{ register_url }}">
                            Utwórz konto na adres e-mail {{ success_user_email }} aby śledzić status Twojego zamówienia<i class="fas fa-user-plus fa-2x mx-3 text-info"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>

{% endblock %}

src/carts/templates/carts/checkout_success_email.html
{% autoescape off %}

Dziękujemy za zakup,

Zamówienie o numerze {{ success_order_id }} zostało przekazane do realizacji.



Zawartość zamówienia:


{% for product in bought_products %}

{{ forloop.counter }} : {{ product.order_title }} : {% if product.promo_active and product.promo_price %}{{ product.promo_price }} zł{% else %}{{ product.price }} zł{% endif %}

{% endfor %}

Koszt produktów :{{ order.products_cost }} zł

Koszt przesyłki:{{ order.shipping_cost }} zł

{% if order.logged_user_promo > 0 %}Rabat:{{ order.logged_user_promo }} %
{% endif %}

Całkowity koszt zamówienia: {{ order.total }} zł

Dane kupującego:

{{ order.billing_address.print_address }}


Adres wysyłki:

{{ order.shipping_address.print_address }}


Prosimy o dokonanie wpłaty zgodnie z poniższymi danymi:

Nr konta: 1234 2345 3456 4566 0000 4566 6660

Kwota: {{ success_order_total }} zł

Tytuł przelewu: {{ success_user_email }}/{{ success_order_id }}



Jeśli posiadasz konto, status swojego zamówienia możesz śledzić w panelu użytkownika:

https://naklisze.pl{% url 'accounts:settings' %}

W przeciwnym przypadku możesz utworzyć konto na na adres e-mail {{ success_user_email }} korzystając z poniższego linka:

https://naklisze.pl{% url 'accounts:register' %}



Zamówienie zostanie wysłane kurierem w przeciągu 3 dni roboczych od zaksięgowania wpłaty.

Pozdrawiamy,

naklisze.pl

{% endautoescape %}

src/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}

{% load static %}

{% url 'carts:update' as update_cart_url %}
{% url 'carts:checkout' as checkout_url %}
{% url 'carts:check_availability' as check_availability_url %}


{% include "carts/snippets/breadcrumbs.html" with page="Koszyk" %}

{% if basket_products %}

    <div class="d-none d-md-block">
        <div class="container-fluid my-3 d-flex justify-content-center">
            <div class="row mx-0 px-0 justify-content-center">
                {% for product in basket_products %}
                {% include "products/snippets/card.html" with instance=product cart=cart %}<p>&nbsp</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container my-5">
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Produkt</th>
                            <th scope="col">Cena</th>
                            <th scope="col"></th>
                            <th scope="col">Usuń</th>
                        </tr>
                    </thead>
                    <tbody>
                          {% for product in basket_products %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><a class="text-dark" href="{{ product.get_absolute_url }}">{{ product.order_title }}</a></td>

                                {% if product.promo_active and product.promo_price %}
                                    <td><strike>{{ product.price }}</strike>&emsp;{{ product.promo_price }} zł</td>
                                {% else %}
                                    <td>{{ product.price }} zł</td>
                                {% endif %}

                                <td>
                                    {% if product.is_multiple %}
                                    {% include "products/snippets/add_another.html" with product=product %}
                                    {% endif %}
                                </td>

                                <td>
                                    {% include "products/snippets/remove_from_cart.html" with product=product cart=cart %}
                                </td>
                            </tr>
                          {% endfor %}
                            <tr>
                              <td colspan="1"></td>
                              <td><p class=""><strong>Suma</strong></p></td>
                                <td><strong>{{ total_price }} zł</strong></td>
                              <td></td>
                            </tr>

                    </tbody>
                </table>
            </div>
        </div>
        {% include "carts/snippets/checkout_start_button.html" with next_url=checkout_url %}
    </div>

{% else %}

    <div class="container my-5">
        <div class="alert alert-secondary my-5 py-5 text-center">
           <h3>Twój koszyk jest pusty! :(</h3>
        </div>
    </div>

{% endif %}

{% endblock %}