src/accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

src/accounts/urls.py
from django.conf.urls import url

from .views import logout_page, GuestRegisterView, SettingsPageView,\
    activation_view, send_activation_mail, LoginView, RegisterView


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(
        r'^activation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activation_view,
        name='activation'
    ),
    url(r'^reactivate/(?P<user>[0-9A-Za-z_\-]+)/(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)/$',
        send_activation_mail,
        name='reactivate'
        ),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', logout_page, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^settings/$', SettingsPageView.as_view(), name='settings'),
    ]

src/sklep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from .views import home_page, AboutPageView, cookies_policy, regulations_page


urlpatterns = [
    url(r'^$', home_page, name='home_page'),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^analytics/', include("analytics.urls", namespace='analytics')),
    url(r'^regulations/$', regulations_page, name='regulations'),
    url(r'^cookies/$', cookies_policy, name='cookies'),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^marketing/', include("marketing.urls", namespace='marketing')),
    url(r'^cart/', include("carts.urls", namespace='carts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/wix/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url

from .views import wix_page

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url='https://biczysko.wix.com/foto')),
    url(r'^$', wix_page, name='wix'),
]

src/accounts/models.py
from django.db import models


class GuestEmail(models.Model):
    email       = models.EmailField()
    active      = models.BooleanField(default=True)
    update      = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserDataUpdateForm(forms.ModelForm):
    username = forms.CharField(
        label='Nazwa użytkownika',
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }),
            required=False
    )

    class Meta:
        model = User
        fields = ['username',]


class GuestForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "E-Mail",
            }
        ),
        label="Twój E-Mail"
    )

    subscribe = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "style": "width: 15px; height: 15px; margin: 5px 6px 6px;"
            }
        ),
        label="Subskrypcja newslettera"
    )

class LoginForm(forms.Form):
    username = forms.CharField(
        label="Twój Login",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Login",
            }))

    password = forms.CharField(label="Twoje hasło", widget=forms.PasswordInput(attrs={
                "class": "form-control",
                "placeholder": "Hasło",
            }))

    def clean_username(self):
        data = self.cleaned_data
        username = data.get('username')
        qs = User.objects.filter(username=username)
        if not qs.exists():
            raise forms.ValidationError("Niepoprawny użytkownik")
        return username




class RegisterForm(forms.Form):
    username = forms.CharField(label="Twój Login", widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "placeholder": "Nazwa",
        }))

    password = forms.CharField(label="Twoje hasło", widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Hasło",
    }))

    password2 = forms.CharField(label="Potwierdź hasło", widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Hasło"
    }))

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "E-Mail",
            }
        ),
        label="Twój E-Mail"
    )

    subscribe = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "style": "width: 15px; height: 15px; margin: 5px 6px 6px;"
            }
        ),
        label="Subskrypcja newslettera",
    )

    def clean_username(self):
        data = self.cleaned_data
        username = data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Użytkownik już istnieje")
        return username

    def clean_password2(self):
        data = self.cleaned_data
        password = data.get('password')
        password2 = data.get('password2')
        if password2 != password:
            raise forms.ValidationError("Niezgodność podanych haseł")
        return data

    def clean_email(self):
        data = self.cleaned_data
        email = data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email znajduje się już w bazie")
        return email

src/accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import DetailView, FormView, UpdateView
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from django.contrib.sites.shortcuts import get_current_site
from django.utils.safestring import mark_safe

from .forms import LoginForm, RegisterForm, GuestForm, UserDataUpdateForm
from .models import GuestEmail
from orders.models import Order
from marketing.models import MarketingPref
from addresses.models import Address
from mixins import NextUrlMixin
from products.models import Product

User = get_user_model()


class SettingsPageView(LoginRequiredMixin, DetailView, UpdateView):
    template_name = "accounts/settings.html"
    redirect_field_name = "next_url"
    form_class = UserDataUpdateForm
    success_url = '#'

    # Newsletter

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        request = self.request
        user = request.user
        context = super(SettingsPageView, self).get_context_data(*args, **kwargs)

        user_orders = Order.objects.user_orders_history(user)
        addresses_qs = Address.objects.filter(billing_profile__email=user.email, current=True)
        billing_addresses = addresses_qs.filter(address_type="billing")
        shipping_addresses = addresses_qs.filter(address_type="shipping")
        unique_viewed_products = self.get_viewed_products(user)

        context['orders'] = user_orders
        context['billing_addresses'] = billing_addresses
        context['shipping_addresses'] = shipping_addresses
        context['viewed_products'] = unique_viewed_products

        return context

    def get_viewed_products(self, user):
        viewed_history = user.objectviewed_set.viewed_products()
        viewed_products_ids = [x.object_id for x in viewed_history]
        # viewed_products = Product.objects.filter(id__in=viewed_products_ids)  # no chronology!
        # viewed_products = [Product.objects.get(id=prod_id) for prod_id in viewed_products_ids]  # proper chronology but no exception handling

        # only proper solution
        viewed_products = []
        for prod_id in viewed_products_ids:
            try:
                viewed_products.append(Product.objects.get(id=prod_id))
            except Product.DoesNotExist:
                pass

        unique_viewed_products = Product.make_qs_unique(viewed_products)

        return unique_viewed_products[:10]

    def post(self, request):
        if request.POST.get('del_address'):
            address_id = request.POST.get('address_id')
            qs = Address.objects.filter(id=address_id)
            if qs:
                address_to_del = qs.first()
                address_to_del.make_stale()
        return redirect('accounts:settings')


class GuestRegisterView(NextUrlMixin, FormView):
    form_class = GuestForm

    def get_context_data(self, **kwargs):
        context = super(GuestRegisterView, self).get_context_data(**kwargs)
        context['title'] =  "Kontynuuj jako gość"
        context['button'] = "Dalej"
        return context

    def form_invalid(self, form):
        request = self.request
        messages.warning(request, 'Formularz został wypełniony niepoprawnie!')
        return super(GuestRegisterView, self).form_invalid(form)

    def form_valid(self, form):
        request = self.request

        email = form.cleaned_data.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id

        # Subscribe to newsletter
        newsletter_subscribe(request, form, guest_email=new_guest_email.email)

        next_path = self.get_next_url()
        return redirect(next_path)


class LoginView(NextUrlMixin, FormView):
    form_class = LoginForm
    template_name = "accounts/auth.html"

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['title'] = "Zaloguj się na konto"
        context['button'] = "Zaloguj"
        context['login'] = "True"
        return context

    def form_invalid(self, form):
        request = self.request
        messages.warning(request, 'Formularz został wypełniony niepoprawnie!')
        return super(LoginView, self).form_invalid(form)

    def form_valid(self, form):
        request = self.request
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user_auth = authenticate(request, username=username, password=password)
        user_obj = User.objects.get(username=username)

        if user_obj.is_active == True:

            if user_auth is not None:
                login(request, user_auth)
                messages.success(request, 'Pomyślnie zalogowano użytkownika {}'.format(username))
                request.session['username'] = username

                if request.session.get('guest_email_id'):
                    del request.session['guest_email_id']

                next_path = self.get_next_url()
                return redirect(next_path)

            else:
                messages.warning(request, 'Niepoprawne hasło!')
                return self.form_invalid(form)

        else:
            messages.warning(
                request,
                'Konto nieaktywne, czy dokonałeś aktywacji? Sprawdź instrukcję wysłaną na adres e-mail: {}'.format(
                    user_obj.email)
            )

            reactivate_url = f'/accounts/reactivate/{user_obj.username}/{user_obj.email}/'

            messages.warning(
                request,
                mark_safe(
                    f"Kliknij <a href='{reactivate_url}'>TUTAJ</a> aby ponownie przesłać link aktywacyjny."
                )
            )

            return self.form_invalid(form)


def logout_page(request):
    if request.session.get('guest_email_id'):
        del request.session['guest_email_id']
        messages.success(request, 'Zakończono sesję gościa')
    else:
        logout(request)
        messages.success(request, 'Pomyślnie wylogowano użytkownika')

    if request.session.get('cart_id'):
        del request.session['cart_id']
    if request.session.get('cart_items_count'):
        del request.session['cart_items_count']

    return redirect('/')


class RegisterView(NextUrlMixin, FormView):
    form_class = RegisterForm
    template_name = "accounts/auth.html"
    default_next = 'accounts:login'

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['title'] = "Utwórz nowe konto"
        context['button'] = "Zarejestruj"
        return context

    def form_invalid(self, form):
        request = self.request
        messages.warning(request, 'Formularz został wypełniony niepoprawnie!')
        return super(RegisterView, self).form_invalid(form)

    def form_valid(self, form):
        request = self.request
        user = form.cleaned_data.get('username')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        new_user = User.objects.create_user(user, email, password)
        new_user.is_active = False
        new_user.save()

        messages.info(
            request,
            'Utworzono konto dla użytkownika {}, aktywuj swoje konto postępując zgodnie z instrukcjami wysłanymi na adres e-mail {}'.format(
                user, email)
        )

        # Subscribe to newsletter
        newsletter_subscribe(request, form, new_user=new_user)

        # Send activation mail
        send_activation_mail(request, user, email)

        next_path = self.get_next_url()
        return redirect(next_path)


def newsletter_subscribe(request, form, new_user=None, guest_email=None):
    newsletter_sub = form.cleaned_data.get('subscribe')
    if newsletter_sub:

        if guest_email:
            MarketingPref.objects.get_or_create(user=None, guest_user_email=guest_email)

        elif new_user:
            MarketingPref.objects.get_or_create(user=new_user)

        messages.success(request, 'Zostałeś dodany do naszego Newslettera!')


def send_activation_mail(request, user, email):
    new_user = User.objects.get(username=user)

    mail_subject = "Aktywuj swoje konto w naklisze.pl"
    current_site = get_current_site(request)
    message = render_to_string('accounts/acc_active_email.html', {
        'user': new_user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
        'token': account_activation_token.make_token(new_user),
    })
    email_msg = EmailMessage(
        mail_subject, message, to=[email]
    )
    try:
        email_msg.send()
    except:
        messages.warning(request, 'Nastąpił błąd przy wysyłaniu wiadomości aktywacyjnej')

    return redirect("accounts:login")


def activation_view(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user_obj = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user_obj = None

    if user_obj and account_activation_token.check_token(user_obj, token):
        user_obj.is_active = True
        user_obj.save()
        messages.success(request, 'Aktywowano konto użytkownika {}, możesz się już zalogować'.format(user_obj.username))
        return redirect('accounts:login')

    else:
        messages.warning(request, 'Niepoprawny link aktywacji konta!')
        return redirect('accounts:register')

src/accounts/templates/accounts/acc_active_email.html
{% autoescape off %}

Witaj {{ user.username }},

Kliknij w poniższy link, aby dokończyć proces aktywacji konta:

http://{{ domain }}{% url 'accounts:activation' uidb64=uid token=token %}

Pozdrawiamy,

sklep naklisze.pl

{% endautoescape %}

src/accounts/templates/accounts/auth.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h2 class="text-secondary">{{ title }}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            {% include "snippets/form.html" with form=form button=button login=login %}
        </div>
    </div>
</div>

{% endblock %}

src/accounts/templates/accounts/settings.html
{% extends "base.html" %}

{% block content %}

{% load static %}

{% url 'regulations' as regulations_url %}
{% url 'about' as about_url %}


<div class="container my-5">

    <div class="text-center text-secondary my-5"><h1>Twoje konto</h1></div>

    <ul id="settings-nav" class="nav nav-tabs nav-justified" role="tablist">

        <li class="nav-item active">
            <a class="nav-link active text-secondary" href="#data" id="data-tab" role="tab" data-toggle="tab" aria-controls="data" aria-expanded="true">
            Dane
            </a>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Pomoc
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item text-secondary" href="{{ about_url }}#contact_form" id="dropdown-contact-tab" aria-controls="dropdownContact">Kontakt</a>
                <a class="dropdown-item text-secondary" href="{{ regulations_url }}" id="dropdown-regulations-tab" aria-controls="dropdownRegulations">Regulamin</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Rachunki
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item text-secondary" href="#dropdown-orders" role="tab" id="dropdown-orders-tab" data-toggle="tab" aria-controls="dropdownOrders">Zamówienia</a>
                <a class="dropdown-item text-secondary" href="#dropdown-addresses" role="tab" id="dropdown-addresses-tab" data-toggle="tab" aria-controls="dropdownAddresses">Adresy</a>
                <a class="dropdown-item text-secondary" href="#dropdown-payment" role="tab" id="dropdown-payment-tab" data-toggle="tab" aria-controls="dropdownPayment">Płatność</a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link text-secondary" href="#recent" id="recent-tab" role="tab" data-toggle="tab" aria-controls="recent" aria-expanded="true">Ostatnio przeglądane produkty</a>
        </li>

    </ul>

    <!-- Content Panel -->
    <div id="clothing-nav-content" class="tab-content">

        <div role="tabpanel" class="tab-pane fade" id="recent" aria-labelledby="recent-tab">
            <h4 class="text-secondary my-5">Produkty, które Cię zainteresowały:</h4>
            <div class="col-lg-6 mx-auto">
                <ul class="list-group list-group-flush">
                {% for product in viewed_products %}
                <li class="list-group-item"><a class="text-dark" href="{{ product.get_absolute_url }}">{{ product.order_title }}</a></li>

                {% endfor %}
                </ul>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="dropdown-orders" aria-labelledby="dropdown-orders-tab">
            <h4 class="text-secondary my-5">Twoje zamówienia:</h4>

            <div class="col-lg-8 mx-auto">
                <table class="table">
                    <thead>
                        <tr>
                          <th scope="col">Nr zamówienia</th>
                            <th scope="col">Data</th>
                          <th scope="col">Koszt</th>
                          <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                          {% for order in orders %}
                          {% include "accounts/settings_snippets/order_modal.html" with modal_id="order{{ order.id }}" order=order bought_products=order.cart.products.all %}
                            <tr>
                                <th scope="row">
                                  <button class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#order{{ order.id }}">{{ order.order_id }}</button>
                                </th>

                                <td>{{ order.timestamp|date:'Y-m-d' }}</td>
                                <td>{{ order.total }} zł</td>
                                <td>{{ order.get_status_display }}</td>
                            </tr>
                          {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="dropdown-addresses" aria-labelledby="dropdown-addresses-tab">
            <div class="row my-2">
                <div class="col-lg-6 text-center">
                    <h4 class="text-secondary my-5">Adresy Wysyłki</h4>
                    {% for address in shipping_addresses %}
                    <div class="row">
                        <div class="col">
                            {% for address_part in address.print_address_html %}
                                &emsp;{{ address_part }}<br>
                            {% endfor %}
                        </div>
                        <div class="col">
                            {% include "accounts/settings_snippets/del_address.html" with action_url=request.build_absolute_uri address_id=address.id %}
                        </div>
                    </div>
                    <hr>

                    {% endfor %}
                </div>
                <div class="col-lg-6 text-center">
                     <h4 class="text-secondary my-5">Dane kupującego</h4>
                    {% for address in billing_addresses %}
                        <div class="row">
                            <div class="col">
                                {% for address_part in address.print_address_html %}
                                    &emsp;{{ address_part }}<br>
                                {% endfor %}
                            </div>
                            <div class="col">
                                {% include "accounts/settings_snippets/del_address.html" with action_url=request.build_absolute_uri address_id=address.id %}
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="dropdown-payment" aria-labelledby="dropdown-payment-tab">
            <h4 class="text-secondary my-5">Dane do płatności:</h4>
            <p>Nr konta: 1234 2345 3456 4566 0000 4566 6660</p>
            <p>Kwota i tytuł przelewu są przesyłane razem z podsumowaniem zamówienia na adres e-mail użytkownika.</p>
        </div>

        <div role="tabpanel" class="tab-pane fade  show active" id="data" aria-labelledby="data-tab">
            {% include "accounts/settings_snippets/user_data_form.html" with form=form %}
        </div>

    </div>
</div>





{% endblock %}